get '/sessions/delete', to: 'sessions#delete'
post '/sessions/create', to: 'sessions#create'
get '/', to: 'home#index'
get '/account/signup', to: 'account#signup'
get '/account/signin', to: 'account#signin'
